# Docker image for building a jar file using maven.
FROM maven:3.8.6-amazoncorretto-18 AS build

WORKDIR /app

COPY pom.xml .
COPY api/pom.xml ./api/pom.xml
COPY lib/pom.xml ./lib/pom.xml
COPY models/pom.xml ./models/pom.xml
COPY services/pom.xml ./services/pom.xml
RUN mvn clean package -Dmaven.main.skip -Dmaven.test.skip

# To package the application
COPY ./ /app
RUN mvn clean package -Dmaven.test.skip


# Docker image that copies jar file from "build" Docker image and executes it.
FROM amazoncorretto:18

WORKDIR /app
COPY --from=build /app/api/target/*.jar /app/api/target/*.jar
COPY --from=build /app/services/target/*.jar /app/services/target/*.jar
COPY --from=build /app/models/target/*.jar /app/models/target/*.jar
COPY --from=build /app/lib/target/*.jar /app/lib/target/*.jar

COPY --from=build ./app/api/target/store-catalog-api-1.0.0-SNAPSHOT.jar /app
EXPOSE 8080
CMD ["java", "-jar", "store-catalog-api-1.0.0-SNAPSHOT.jar"]