apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-catalog
  template:
    metadata:
      labels:
        app: store-catalog
    spec:
      containers:
        - image: metatheory/store-catalog:2022-11-09-11-10-34
          name: store-catalog
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://mouse.db.elephantsql.com:5432/sqpivtck
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: sqpivtck
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-password
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: store-catalog
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: store-catalog