kumuluzee:
  name: store-catalog-microservice
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/StoresDS
      connection-url: jdbc:postgresql://localhost:5432/stores
      username: dbuser
      password: postgres
      max-pool-size: 20
  graphql:
    schema:
      include-scalars: true
      include-schema-definition: true
      include-directives: true
      include-introspection-types: true
    metrics:
      enabled: true